#Created by: Quintin Leong
#File: Makefile
#CMPS104A


all: 
	g++ -c -std=gnu++11 main.cpp stringset.cpp
	g++ -ooc main.o stringset.o

clean:
	rm main.o stringset.o

spotless:
	rm main.o stringset.o oc

deps:
	g++ -c -std=gnu++11 main.cpp stringset.cpp

ci:
	ci -u main.cpp
	ci -u stringset.cpp
